In [1]:
import pandas as pd

In [2]:
import requests

# to create http rqst

In [9]:
response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1")

In [11]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
  'genre_ids': [16, 28, 12, 14],
  'id': 980431,
  'title': 'Avatar Aang: The Last Airbender',
  'original_language': 'en',
  'original_title': 'Avatar Aang: The Last Airbender',
  'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
  'popularity': 110.9348,
  'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
  'release_date': '2026-07-24',
  'softcore': False,
  'video': False,
  'vote_average': 9.227,
  'vote_count': 897},
 {'adult': False,
  'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
  'genre_ids': [35, 10749],
  'id': 1632181,
  'title': 'Accidental Partners',
  'original_language': 'es',
  'original_title': 'Socias por accidente',
  'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
  'popularity': 24.8184,
  'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
  'release_date': '2026-03-12',
  'softcore': False,
  'video': False,
  'vote_average': 8.9,
  'vote_count': 354},
 {'adult': False,
  'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
  'genre_ids': [12, 16, 10751, 14],
  'id': 1007757,
  'title': 'Swapped',
  'original_language': 'en',
  'original_title': 'Swapped',
  'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
  'popularity': 50.529,
  'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
  'release_date': '2026-05-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.881,
  'vote_count': 2111},
 {'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'title': 'The Shawshank Redemption',
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 88.7998,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.728,
  'vote_count': 31074},
 {'adult': False,
  'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
  'genre_ids': [16, 28, 14],
  'id': 1311031,
  'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
  'original_language': 'ja',
  'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
  'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
  'popularity': 92.4348,
  'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
  'release_date': '2025-07-18',
  'softcore': False,
  'video': False,
  'vote_average': 8.734,
  'vote_count': 1886},
 {'adult': False,
  'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'title': 'The Godfather',
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 57.6588,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'softcore': False,
  'video': False,
  'vote_average': 8.686,
  'vote_count': 23371},
 {'adult': False,
  'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
  'genre_ids': [10402, 18],
  'id': 936075,
  'title': 'Michael',
  'original_language': 'en',
  'original_title': 'Michael',
  'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
  'popularity': 81.9152,
  'poster_path': '/2AvgnCwCakNiJqWZqaQhdGjWNey.jpg',
  'release_date': '2026-04-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.675,
  'vote_count': 4076},
 {'adult': False,
  'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
  'genre_ids': [878, 12],
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_language': 'en',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'popularity': 127.2495,
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.654,
  'vote_count': 7153},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'title': 'The Godfather Part II',
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 30.7144,
  'poster_path': '/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg',
  'release_date': '1974-12-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.572,
  'vote_count': 14192},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'title': "Schindler's List",
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 36.2824,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 17757},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'title': '12 Angry Men',
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 27.3162,
  'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
  'release_date': '1957-04-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.568,
  'vote_count': 10248},
 {'adult': False,
  'backdrop_path': '/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg',
  'genre_ids': [18, 10749],
  'id': 1232449,
  'title': 'Young Hearts',
  'original_language': 'nl',
  'original_title': 'Young Hearts',
  'overview': '14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neighbour of the same age, Alexander, Elias is confronted with his burgeoning sexuality.',
  'popularity': 16.7894,
  'poster_path': '/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg',
  'release_date': '2024-10-26',
  'softcore': False,
  'video': False,
  'vote_average': 8.567,
  'vote_count': 304},
 {'adult': False,
  'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
  'genre_ids': [28, 80, 53],
  'id': 155,
  'title': 'The Dark Knight',
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 61.3608,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'softcore': False,
  'video': False,
  'vote_average': 8.534,
  'vote_count': 36433},
 {'adult': False,
  'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'title': 'Spirited Away',
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 31.842,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 18714},
 {'adult': False,
  'backdrop_path': '/gqTz24ZRsCP6AKjARmEivY7m0cK.jpg',
  'genre_ids': [16, 28, 10749, 14],
  'id': 1218925,
  'title': 'Chainsaw Man - The Movie: Reze Arc',
  'original_language': 'ja',
  'original_title': '劇場版 チェンソーマン レゼ篇',
  'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
  'popularity': 30.4075,
  'poster_path': '/crBfxNvvsQV3rATX12EuX4W9ECo.jpg',
  'release_date': '2025-09-19',
  'softcore': False,
  'video': False,
  'vote_average': 8.527,
  'vote_count': 1124},
 {'adult': False,
  'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'title': 'The Green Mile',
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 33.045,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.506,
  'vote_count': 19636},
 {'adult': False,
  'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'title': 'Dilwale Dulhania Le Jayenge',
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 13.9509,
  'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
  'release_date': '1995-10-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 4613},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'title': 'The Lord of the Rings: The Return of the King',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 50.5079,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.504,
  'vote_count': 27114},
 {'adult': False,
  'backdrop_path': '/vbC0rzdrb7Ohc2TkbEbxtOABECe.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'title': 'Parasite',
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 37.6515,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'softcore': False,
  'video': False,
  'vote_average': 8.49,
  'vote_count': 21115},
 {'adult': False,
  'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'title': 'Your Name.',
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 27.3264,
  'poster_path': '/vfJFJPepRKapMd5G2ro7klIRysq.jpg',
  'release_date': '2016-07-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.485,
  'vote_count': 12869}]

In [13]:
pd.DataFrame(response.json()['results']).head(2)

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg,"[16, 28, 12, 14]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",110.9348,/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg,2026-07-24,False,False,9.227,897
1,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,24.8184,/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg,2026-03-12,False,False,8.900,354

In [17]:
pd.DataFrame(response.json()['results']).head()[['id','title','popularity','release_date','vote_average','vote_count']]

,id,title,popularity,release_date,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,110.9348,2026-07-24,9.227,897
1,1632181,Accidental Partners,24.8184,2026-03-12,8.900,354
2,1007757,Swapped,50.5290,2026-05-01,8.881,2111
3,278,The Shawshank Redemption,88.7998,1994-09-23,8.728,31074
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,92.4348,2025-07-18,8.734,1886

In [18]:
df = pd.DataFrame(response.json()['results'])[['id','title','popularity','release_date','vote_average','vote_count']]

In [20]:
df.head()

,id,title,popularity,release_date,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,110.9348,2026-07-24,9.227,897
1,1632181,Accidental Partners,24.8184,2026-03-12,8.900,354
2,1007757,Swapped,50.5290,2026-05-01,8.881,2111
3,278,The Shawshank Redemption,88.7998,1994-09-23,8.728,31074
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,92.4348,2025-07-18,8.734,1886

In [25]:
df = pd.DataFrame()

In [26]:
df

Empty DataFrame
Columns: []
Index: []

In [32]:
for i in range(1, 429):
    
    # Make the API requests
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    
    # Check if the request was successful (status code 200)
    if response.status_code == 200:
        
        # Extract relevant data from the response
        temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]
        
        # Append the data to the main DataFrame
        df = pd.concat([df, temp_df], ignore_index=True)
    else:
        print(f"Failed to retrieve data for page {i}")

In [33]:
df.shape

(18560, 7)

In [34]:
df.to_csv('movies.csv')