In [1]:
import pandas as pd

# Working with JSON

In [3]:
pd.read_json('test.json')

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]

In [4]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-19,1787097601,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-19,1787097601,0.0383
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-19,1787097601,0.6850
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-19,1787097601,0.8380
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-19,1787097601,3.8300
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-19,1787097601,2.4800
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-19,1787097601,0.1700
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-19,1787097601,0.1970
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-19,1787097601,0.2790
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-19,1787097601,0.2790

# Working with SQL

!pip install mysql.connector

# mysql.connector is a library

In [16]:
import mysql.connector

In [19]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [20]:
pd.read_sql_query("SELECT * FROM city",conn)

C:\Users\Admin\AppData\Local\Temp\ipykernel_14724\374620591.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city",conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]