In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('train.csv')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
import sys
!{sys.executable} -m pip install ydata-profiling

Requirement already satisfied: ydata-profiling in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (2.3.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (2.3.5)
Requirement already satisfied: minify-html>=0.15.0 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (2.34.2)
Requirement already satisfied: tqdm<5,>=4.66.3 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (4.70.0)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (4.6.0)
Requirement already satisfied: imagehash==4.3.2 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from imagehash==4.3.2->ydata-profiling) (12.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.3)
Requirement already satisfied: joblib>=0.14.1 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.7.22)
Requirement already satisfied: patsy>=0.5.6 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: colorama in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Requirement already satisfied: puremagic in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\miniconda3\envs\profiling\Lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [8]:
from ydata_profiling import ProfileReport
prof=ProfileReport(df)
prof.to_file(output_file='output.htmll')

ModuleNotFoundError: No module named 'pkg_resources'

In [9]:
import sys
!{sys.executable} -m pip install "setuptools<82"


# This step i had to do bcoz of dependacies were not compatible with the library

Collecting setuptools<82
  Downloading setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Downloading setuptools-81.0.0-py3-none-any.whl (1.1 MB)
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   ---------------------------------------- 1.1/1.1 MB 9.4 MB/s  0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 84.0.0
    Uninstalling setuptools-84.0.0:
      Successfully uninstalled setuptools-84.0.0
Successfully installed setuptools-81.0.0

In [1]:
import pkg_resources
print("pkg_resources works!")

pkg_resources works!

C:\Users\Admin\AppData\Local\Temp\ipykernel_3124\2101947353.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('train.csv')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
from ydata_profiling import ProfileReport

prof = ProfileReport(df)
prof.to_file(output_file="output.html")

Summarize dataset:  35%|███▌      | 6/17 [00:00<00:00, 24.04it/s, Describe variable: Embarked]
100%|██████████| 12/12 [00:00<00:00, 156.09it/s]00:00, 21.95it/s, Describe variable: Embarked]
Summarize dataset: 100%|██████████| 47/47 [00:03<00:00, 11.95it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:04<00:00,  4.12s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.71s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 58.74it/s]